"
" vimrc
"

execute pathogen#infect()
execute pathogen#helptags()

" Use Vim instead of Vi settings
set nocompatible

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Make backspace delete over anything
set backspace=indent,eol,start

" Color settings
" =============================================================================

syntax on
syntax enable

set background=dark
"set background=light

"colorscheme slate
colorscheme solarized

" =============================================================================

set undodir=C:/Users/kgerig/vimfiles/undo//
set backupdir=C:/Users/kgerig/vimfiles/backup//
set directory=C:/Users/kgerig/vimfiles/swap//

" tabs
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set expandtab
set tabstop=4
set shiftround

" general display settings
set number
set relativenumber
nnoremap <leader><space> :noh<cr>
set ruler
set cmdheight=2
set hlsearch
set showmode
set showcmd
set wildmenu
set showtabline=2

set gfn=Consolas:h12:cANSI

nnoremap j gj
nnoremap k gk

" remove the menu bar
set guioptions-=m

" remove the toolbar
set guioptions-=T

"remove the righthand scrollbar
set guioptions-=r

map <C-n> :NERDTreeToggle<CR>

