" _gvimrc for Windows

" first disable Vi compatibilty mode
set nocompatible

" change leader key
let mapleader = "," "sets comma as my leader key, instead of \

" color settings
" Built-in schemes
    "colorscheme darkblue   "minor ugh
    "colorscheme desert     "not TERRIBLE...
    "colorscheme elflord    "ummm, very purple...
    "colorscheme evening    "no thanks, too pastel-ey
    "colorscheme peachpuff  "actually, not bad, a bit bright
    "colorscheme ron        "a bit green/future-y, but ok?
    "colorscheme slate      "ok, but highlights are weird

" Custom/added colorschemes
    "colorscheme solarized  "a sane colorscheme...thank you Ethan
    "colorscheme badwolf
    "colorscheme jellybeans
    "colorscheme monokai
    colorscheme PerfectDark
    
" font settings
set guifont=Ubuntu_Mono:h12:cANSI

" general display settings
set number
set hlsearch
set incsearch
nnoremap <leader><space> :noh<cr>
set ruler
"set guioptions-=m "toggle menu bar
set guioptions-=T "toggle toolbar
set guioptions-=r "toggle scrollbars
syntax enable

" editor settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set shiftround
set expandtab
set backspace=indent,eol,start
set autoindent

" environment (?) settings
filetype plugin indent on
set browsedir=current
set noswapfile
set shell=C:\cygwin64\bin\bash.exe\ --login\ -i\
set shellquote=
set shellxquote=
set shellcmdflag=-c

" change working directory to local drive
cd C:\Users\kgerig
