# set TERM
set default-terminal "screen-256color"

# tmux key-bindings

source $HOME/.tmux.f-keys.enable

# Status bar settings
set -g status-position top
set -g status-style bg=black,fg=yellow
set -g window-status-current-style bg=white,fg=brightblack
set -g window-status-separator " | "

# set terminal title
set -g set-titles on
set -g set-titles-string "${USER}@#H"

setw -g mode-keys vi
set -g status-keys vi

set -g display-time 3000
set -g escape-time 100

set -g prefix2 F12
unbind-key C-b
set -g prefix 'C-\'
bind-key 'C-\' send-prefix

# non-f-key key-bindings

bind-key -n M-Left previous-window
bind-key -n M-Right next-window
bind-key -n M-Up switch-client -p
bind-key -n M-Down switch-client -n

bind-key -n S-Left select-pane -L
bind-key -n S-Right select-pane -R
bind-key -n S-Up select-pane -U
bind-key -n S-Down select-pane -D

bind-key -n M-S-Left resize-pane -L
bind-key -n M-S-Right resize-pane -R
bind-key -n M-S-Up resize-pane -U
bind-key -n M-S-Down resize-pane -D

bind-key -T prefix Escape copy-mode

unbind p
bind-key -T prefix p paste-buffer
bind-key -t vi-copy y copy-selection -x
bind-key -t vi-copy v begin-selection
